version: "3.8"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy  
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@db/customer_db
    volumes:
      - ./logs:/app/logs
    command: >
      sh -c "python migrations.py init &&
             python migrations.py upgrade &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customer_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "0.0.0.0", "-u", "root", "-proot"]  
      interval: 5s  
      timeout: 5s   
      retries: 10   

volumes:
  db_data: